### ISSUE TITLE
Requires new line function

### ISSUE THREAD

**Issue by C-YooJin** [C-YooJin/lavender#4]
![image](https://user-images.githubusercontent.com/30011635/101726359-bd2a5a00-3af5-11eb-907c-62c0801f0dec.png)

New lines are not supported yet.

**Comment by C-YooJin** [comment]
What I entered is

```
아무리 생각해도 난 너를
아무리 생각해도 난 너를
잊은 듯 눈 감아도 난 너를
아닌 듯 돌아서도 난 너를
조금만 솔직해도 나 너를
그렇게 아파하도록 너를


나 이대로 더 있으면
이대로 머무르면 너를 더 사랑할 것 같아
```

But it was posted without a new line.

**Comment by bolam-o** [comment]
Just add element style `white-space`
Try to with this code!

``` html
<p class="card-text" style="white-space: pre-wrap" th:text="${post.content}"></p>
```

[About `white-space` attribute](https://developer.mozilla.org/ko/docs/Web/CSS/white-space)

**Comment by C-YooJin** [comment]
![image](https://user-images.githubusercontent.com/30011635/102880119-30d14d00-448e-11eb-9a64-389913e6aa26.png)
👍
